spring:
  application:
    name: eukera-service
server:
  port: 8302
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty:  0
zuul:
  prefix: /api
  routes:
    database-service:
      path: /database-service/**
      url:  http://localhost:8300
    stock-service:
      path: /stock-service/**
      url:  http://localhost:8301

